name: math4life
type: docker-compose
repo:
  url: https://github.com/agntsupport/math4life
  branch: main
compose:
  file: docker-compose.yml
services:
  - name: frontend
    port: 3000
    domains:
      - math4life.82.197.94.27.nip.io
    health_check:
      path: /
      interval: 30
  - name: backend
    port: 4000
    health_check:
      path: /api/health
      interval: 30
  - name: postgres
    internal: true
  - name: redis
    internal: true
env:
  NODE_ENV: production
  DB_USER: math4life
  DB_PASSWORD: math4life_secure
  DB_NAME: math4life