version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      target: production
    container_name: math4life-frontend-prod
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=/api
    networks:
      - math4life-network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      target: production
    container_name: math4life-backend-prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=math4life
      - DB_PASSWORD=math4life_prod_secure
      - DB_NAME=math4life
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret_change_in_production_123456
      - SESSION_SECRET=your_session_secret_change_in_production_123456
      - FRONTEND_URL=http://localhost
    networks:
      - math4life-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: math4life-postgres-prod
    environment:
      - POSTGRES_USER=math4life
      - POSTGRES_PASSWORD=math4life_prod_secure
      - POSTGRES_DB=math4life
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - math4life-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: math4life-redis-prod
    volumes:
      - redis_data:/data
    networks:
      - math4life-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: math4life-nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.simple.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - math4life-network
    restart: unless-stopped

networks:
  math4life-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: