version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.debug
    container_name: math4life-debug
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  app_data: