version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      target: development
    container_name: math4life-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://82.197.94.27:4000/api
      - VITE_SOCKET_URL=http://82.197.94.27:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - math4life-network
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0 --port 3000

  backend:
    build: 
      context: ./backend
      target: development
    container_name: math4life-backend-dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=math4life
      - DB_PASSWORD=math4life_dev
      - DB_NAME=math4life
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGIN=http://82.197.94.27:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - math4life-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: math4life-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=math4life
      - POSTGRES_PASSWORD=math4life_dev
      - POSTGRES_DB=math4life
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - math4life-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: math4life-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - math4life-network
    restart: unless-stopped

networks:
  math4life-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: