version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.simple
    container_name: math4life-app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
      - DB_USER=${DB_USER:-math4life}
      - DB_PASSWORD=${DB_PASSWORD:-math4life_prod}
      - DB_NAME=${DB_NAME:-math4life}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_change_in_production}
      - SESSION_SECRET=${SESSION_SECRET:-your_session_secret_change_in_production}
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - math4life-network

  postgres:
    image: postgres:15-alpine
    container_name: math4life-postgres
    environment:
      - POSTGRES_USER=${DB_USER:-math4life}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-math4life_prod}
      - POSTGRES_DB=${DB_NAME:-math4life}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - math4life-network

  redis:
    image: redis:7-alpine
    container_name: math4life-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - math4life-network
    command: redis-server --appendonly yes

networks:
  math4life-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: